export enum MISSION_STATUS {
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
}

export enum TASK_STATUS {
  PENDING = "PENDING",
  DONE = "DONE",
}

export enum SESSION_END_REASON {
  MISSION_COMPLETED = "MISSION_COMPLETED",
  EARLY_EXIT = "EARLY_EXIT",
  TIME_LIMIT_REACHED = "TIME_LIMIT_REACHED",
}

export enum SUBSCRIPTION_STATUS {
  ACTIVE = "ACTIVE",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED",
  BILLING_ISSUE = "BILLING_ISSUE",
}
