export enum MISSION_STATUS {
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
}

export enum TASK_STATUS {
  PENDING = "PENDING",
  DONE = "DONE",
}

export enum SESSION_END_REASON {
  MISSION_COMPLETED = "MISSION_COMPLETED",
  EARLY_EXIT = "EARLY_EXIT",
}
